# - shell: make bootstrap

- clean: ['~']

- clean: ['~/.local/share/supercollider/downloaded-quarks/dirt-samples']

# linking dotfiles
- link:
    ~/.profile:
      force: true
      path: llipuru/.profile
    ~/.oh-my-zsh/themes/lalis.zsh-theme: lalis.zsh-theme
    ~/.taskrc: .taskrc
    ~/.zshrc:
      path: .zshrc
      force: true
    ~/.config/alacritty/alacritty.yml:
      create: true
      path: common/alacritty.yml
    ~/.config/kak/kakrc:
      path: kakrc
      create: true
    ~/.config/init.vim: init.vim
    ~/.config/musescore/musescore2.ini: musescore2.ini
    ~/.config/musescore/musescore3.ini: common/musescore3.ini
    ~/.config/supercollider:
      glob: true
      force: true
      path: supercollider/*
    ~/.local/share/supercollider/downloaded-quarks/dirt-samples: # tidal samples
      glob: true
      path: ~/samples/*
    ~/.config/vscodium/user:
      glob: true
      force: true
      path: code/*
    # /usr/bin/basecamp: /home/lalis/downloads/basecamp-linux-x64/basecamp
    # ~/start_jack.sh: common/start_jack.sh
    ~/.profile: common/.profile # fucking multilanguage keyboard config bullshit
    # ~/.xresources:
      # relink:
      # path: llipuru/.xresources
    ~/.config/tidal/boot.tidal:
      create: true
      path: tidal/boot.tidal
    ~/.config/fontconfig/conf.d/01-emoji.conf:
      create: true
      path: common/01-emoji.conf
    ~/.config/zathura/zathurarc:
      create: true
      path: common/zathurarc
    ~/.config/starship.toml: common/starship.toml
    ~/.gradle/gradle.properties: common/ribon.gradle.properties
    # /etc/asound.conf:
    #   path: common/asound.conf
    #   force: true
