

# Linking Dotfiles
- link:
    ~/.profile:
      force: true
      path: regolith/.profile
    # ~/.config/regolith/i3/config:
    #   force: true
    #   create: true
    #   path: regolith/i3config
    # ~/.Xresources-regolith:
    #   force: true
    #   path: regolith/Xresources-regolith
    ~/.oh-my-zsh/themes/lalis.zsh-theme:
      path: common/lalis.zsh-theme
      force: true
    ~/.taskrc: .taskrc
    ~/.zshrc:
      path: .zshrc
      force: true
    ~/.config/alacritty/alacritty.yml:
      create: true
      path: common/alacritty.yml
    ~/.config/kak/kakrc:
      path: common/kakrc
      create: true
      force: true
    ~/.config/init.vim:
      path: common/init.vim
      force: true
    ~/.config/MuseScore/MuseScore2.ini:
      path: common/MuseScore2.ini
      force: true
    ~/.config/MuseScore/MuseScore3.ini:
      path: common/MuseScore3.ini
      force: true
    # VSCodium
    ~/.config/VSCodium/User:
      path: common/code/*
      glob: true
      force: true
    ~/.config/zathura/zathurarc: common/zathurarc
    # Gaming Stuff
    /lib/udev/rules.d/99-steam-controller-perms.rules:
        create: true
        force: true
        path: regolith/steam-controller-config
    ~/.config/SuperCollider:
      path: common/supercollider/*
      glob: true
      force: true
    # Folder Shortcuts
    ~/screcs: ~/.local/share/SuperCollider/Recordings
    ~/dirtsamples: ~/.local/share/SuperCollider/downloaded-quarks/Dirt-Samples
    # OBS
    ~/.config/obs-studio:
      path: common/obs/*
      glob: true
      force: true
    ~/.config/REAPER/ProjectTemplates/tidal-tracking.RPP:
      path: tidal-tracking.RPP
      force: true


# Clone Kakoune Plugin Manager
- shell:
  - "if [ ! -d ~/.config/kak/plugins/plug.kak ]; then git clone https://github.com/robertmeta/plug.kak.git ~/.config/kak/plugins/plug.kak; fi"