- clean: ['~']
- clean: ['~/.local/share/SuperCollider/downloaded-quarks/Dirt-Samples']

- shell:
  # - [dotbot -d . -c scripts/ppas.conf.yaml, Adding PPAs]
  # - [dotbot -d . -c scripts/ fonts.conf.yaml, Adding Fonts]
  - [bash scripts/install-vim-plug.sh, Installing Vim-Plug]
  - [bash scripts/install_linuxbrew.sh, Installing Vim-Plug]
  - [dotbot -d . -c scripts/node.conf.yaml, Installing node & packages]
  # - [dotbot -d . -c scripts/react-native.conf.yaml, Installing node & packages]
  - [dotbot -d . -c scripts/shell.conf.yaml, Configuring shell]
  - [dotbot -d . -c scripts/terminal.conf.yaml, Configuring Terminal Tools]
  - [dotbot -d . -c scripts/i3.conf.yaml, Configuring i3-blocks]
  # - [dotbot -d . -c scripts/regolith.conf.yaml, Configuring Media Tools]
  - [dotbot -d . -c scripts/media.conf.yaml, Configuring Media Tools]
  - [dotbot -d . -c scripts/supercollider.conf.yaml, Installing SuperCollider]
  - [dotbot -d . -c scripts/live-coding.conf.yaml, Configuring Live Coding Tools]
  - [dotbot -d . -c scripts/gaming.conf.yaml, Configuring Gaming Tools]

# Installing YTT
- shell:
  - [brew tap k14s/tap, Adding ytt to taps]
  - [brew install ytt kbld kapp imgpkg kwt vendir, Installing ytt]

- shell:
  - [dotbot -d . -c llipuru-regolith-dotfiles.conf.yaml, Linking Configs]

# Link local.properties to Android Projects
# - link:
#   ~/git/Rocket.Chat.ReactNative/android/local.properties: common/local.properties
#
