
# Linking Dotfiles
- link:
    ~/.profile:
      force: true
      path: regolith/.profile
    ~/.oh-my-zsh/themes/lalis.zsh-theme:
      path: common/lalis.zsh-theme
      force: true
    ~/.zshrc:
      path: common/.zshrc-pi
      force: true
    ~/.config/kak/kakrc:
      path: common/kakrc-pi
      create: true
      force: true
    ~/.config/init.vim:
      path: common/init.vim
      force: true
    # Personal SC Libs
    ~/.config/SuperCollider/startup.scd: common/supercollider/startup.scd
    ~/.config/SuperCollider/cycles.scd: common/supercollider/cycles.scd
    ~/.config/tidal/boot.tidal:
      create: true
      path: ~/git/libtidal/boot.tidal
    # Folder Shortcuts
    ~/screcs: ~/.local/share/SuperCollider/Recordings
    ~/dirtsamples: ~/.local/share/SuperCollider/downloaded-quarks/Dirt-Samples
    ~/.asoundrc:
      path: common/pi/asound.conf
      force: true
    # Pi's JackDRC uses hw:2 (meant to be Elektron Model Cycles)
    ~/.jackdrc:
      path: common/pi/jackdrc
      force: true
    # TMUX config
    ~/.tmux.conf:
      path: common/tmux.conf


# Clone Kakoune Plugin Manager
- shell:
  - "if [ ! -d ~/.config/kak/plugins/plug.kak ]; then git clone https://github.com/robertmeta/plug.kak.git ~/.config/kak/plugins/plug.kak; fi"
