
# Linking Dotfiles
- link:
    ~/.profile:
      force: true
      path: regolith/.profile
    ~/.oh-my-zsh/themes/lalis.zsh-theme:
      path: common/lalis.zsh-theme
      force: true
    ~/.zshrc:
      path: common/.zshrc-pi
      force: true
    ~/.config/kak/kakrc:
      path: common/kakrc
      create: true
      force: true
    ~/.config/init.vim:
      path: common/init.vim
      force: true
    ~/.config/SuperCollider:
      path: common/supercollider/*
      glob: true
      force: true
    ~/.config/tidal/boot.tidal:
      create: true
      path: ~/git/libtidal/boot.tidal
    # Folder Shortcuts
    ~/screcs: ~/.local/share/SuperCollider/Recordings
    ~/dirtsamples: ~/.local/share/SuperCollider/downloaded-quarks/Dirt-Samples
