- clean: ['~']
- clean: ['~/.local/share/SuperCollider/downloaded-quarks/Dirt-Samples']

- shell:
  # - [bash scripts/install_linuxbrew.sh, Installing Linuxbrew]
  # - [dotbot -d . -c scripts/ppas.conf.yaml, Adding PPAs]
  # - [dotbot -d . -c scripts/fonts.conf.yaml, Adding Fonts]
  - [bash scripts/build-ninjam.sh, Installing CNinjam]
  - [dotbot -d . -c scripts/node.conf.yaml, Installing node & packages]
  - [dotbot -d . -c scripts/terminal.conf.yaml, Configuring Terminal Tools]
  - [dotbot -d . -c scripts/live-coding.conf.yaml, Configuring Live Coding Tools]

- shell:
  - ["if [ ! -e ~/git/libtidal ]; git clone https://github.com/ghalestrilo/libtidal ~/git/libtidal; fi", Installing thefuck]

- shell:
  - [dotbot -d . -c pi-dotfiles.conf.yaml, Linking Configs]
