- clean: ['~']
- clean: ['~/.local/share/SuperCollider/downloaded-quarks/Dirt-Samples']

- shell:
  # - [bash scripts/build-ninjam.sh, Installing CNinjam]
  - [bash scripts/install-vim-plug.sh, Installing Vim-Plug]
  - [dotbot -d . -c scripts/node.conf.yaml, Installing node & packages]
  - [dotbot -d . -c scripts/terminal.conf.yaml, Configuring Terminal Tools]
  - [bash scripts/build-supercollider.sh, Building Supercollider]
  - [bash scripts/build-sc3-plugins.sh, Building SC3 Plugins]
  - [bash scripts/build-amidiauto.sh, Building amidiauto]
  - [bash scripts/setup-autostart.sh, Setting up SC to start on boot]
  - [dotbot -d . -c scripts/live-coding.conf.yaml, Configuring Live Coding Tools]

- shell:
  - ["if [ ! -e ~/git/libtidal ]; git clone https://github.com/ghalestrilo/libtidal ~/git/libtidal; fi", Cloning LibTidal]

- shell:
  - [dotbot -d . -c pi-dotfiles.conf.yaml, Linking Configs]
